language: node_js
node_js:
- 7.8.0
script: npm run build --production
before_deploy: tar -zcvf $TRAVIS_BUILD_DIR/lime-app-$TRAVIS_BRANCH.tar.gz build
deploy:
  provider: releases
  file: "$TRAVIS_BUILD_DIR/lime-app-$TRAVIS_BRANCH.tar.gz"
  skip_cleanup: true
  on:
    tags: true
  user:
    secure: KGyEnpOAssZlXu6vIX9Rcrguj6poJrD785s77m2GNuHWbIaO+T6slpRDN/xwFZ1boSCIVq7eTs7WKsBZ6P0T5zwp0b3wSrrxAIO9gOeXsZ0JhkzoOAOhUYUIi3mNefnD7MrqhxtJJaoeKbN+jocxQpBe6YgdlZo6h4YCwkWMm3nOHqyf8TRkEWD+DUqTNlX9qbE0QVRJ3JqyPYJeJhKyo9WfFsuAcvj9S+9+MPTvKhJ5NpiDLhma0E5aoloDBzSvURMafvMrH53COAAbgcaY3AFfWX6FapCdM2tfK6OvqIywiI0QMPCE6Vf1DYNVgSiz91yUl48LX0HE2heEp4euViRmqA+xHhRoZakLuIdz11LVR4vCMNLIv63iVc4o9KLJW2YIB3mT7QJ6UCNrwQ4fvj53KTGQF8nYQq7isrC9nyNinEpeosfxtpIRv7Ozu8NlJGO7IzUnutXugSNJy10zDwvyJuZBgm12yr51mkcO/TdVyMGTcFH4SE7WEkUDPVXWs2STHesj5rHT8xEbfetMz/tgKKIkjBMafsLDZKx3OoEZvEsZnWTYT0bQey68guK5wtpYxfHjqT8hBIF/VNvAuCqUQOONekoDIdtSf9BnlNWFFOZiKP9CPA1kbdM4sHFPukLnalKZM0jfY1eGYqA4rc8ld2nLLTslX3wrJ6RiZXI=
  password:
    secure: ijBY23BdcqWXrqbKGzzdKjVqfvCraLVPfO2O8asxpBgHZoZoq1Idy6mcXEThJTvXflR6EDVayPLvInkvb6dfqxW4ogZyiM6863oEsEIoxHgdJphwPPdwk6tl4wqDIBQElyKvFRnKy+VWKU8qtfmw84SOST6knaVXPA398jrujHVkCYLqKYqdBloysqEgMBeAEMfqHo+vquGEXBwPX+CUwu8mElAkO3qsuOi4nZJMftXp056n1JTAnh4eV5+mjwbFCDOCR/4uaevwAoycBiMDHD1amUoxLMvAWvYl7jNo1Y1mpl0NPo5FOQ9nTuVwBfCaZzURdTU4aJl8qCfSRWl3Td2muNPjdG90AsnwSZad/dJxig1ci/m4sfM30yfIH/s0Ojrw2d17O4c4fMvthS6ja41gfX2pjE2ijOLJIgJ4+6Ia2hCFaQT7wCPZugfjHbO+AMU6ABz3zdHl2voppbS4cj/AysNESatIVpuVSRH8ZHHrp6U6CE2ebUm2ph2ctfPQeI1ipzpVWwtaUS95OJ9Y5cqvgNfSkTiQk9NEtjhq22cnoa0sV2nzNkwYS2smcUQj0n9wd/h/r07aW1lcRoxEV+DkZG9yKnXUnOjv4RmYWpxB1bLwfXp+/ycoDRG1ehr4KJ1FRf3AIQRkb6ZIb0Zbd937K/h9e9yBh9qPYtO08ko=
